services:
  - type: web
    name: resume-reviewer-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: cd app && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: /opt/render/project/src/app
